# -*- coding: utf-8 -*-
"""Embeddings.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1O6Lgw8P8GRTAmDov1J_MIoB0s6IyzE0n
"""

pip install -q sentence-transformers chromadb langchain langchain-community langchain_google_genai

# Importing the langchain documents

import pickle

with open("documents_32.pkl", "rb") as f:
    docs = pickle.load(f)

type(docs[0])

len(docs)

from langchain.schema import Document
from langchain.text_splitter import RecursiveCharacterTextSplitter

from sentence_transformers import SentenceTransformer

from langchain_community.embeddings import HuggingFaceEmbeddings
from langchain_community.vectorstores import Chroma

# Chunking the Documents

text_splitter = RecursiveCharacterTextSplitter(chunk_size=1000, chunk_overlap=200)
chunked_docs = text_splitter.split_documents(docs)

len(chunked_docs)

# Initialing Embeddings

embedding = HuggingFaceEmbeddings(model_name='all-MiniLM-L6-v2')

# Initialize the chroma database

vectorstore = Chroma.from_documents(
    documents=chunked_docs,
    embedding=embedding,
    persist_directory="chroma_db_32"
)

import shutil

# Creating a zip archive of the directory to download it.
shutil.make_archive('chroma_db_32_backup', 'zip', 'chroma_db_32')

